apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drop-the-mic.fullname" . }}-operator
  labels:
    {{- include "drop-the-mic.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
